Repository AY2425S2-CS2103T-T13-1/tp, pull requests merged in 2025-03, with the labels that each got.

#22 Add CloudKai's photo
  docs/images/cloudkai.png
Labels: type.Task

#23 Branch an wei photo
  docs/images/anwe11.png
Labels: type.Task

#32 Update AboutUs.md and made portfolio file
  docs/AboutUs.md
  docs/team/zonghua.md
Labels: type.Task

#31 Update aboutus and Add cloudkai.md
  docs/AboutUs.md
  docs/team/cloudkai.md
Labels: type.Task

#34 Update About Us page
  docs/AboutUs.md
  docs/team/anwei.md
Labels: type.Task

#46 Update NFRs in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#52 Update user stories
  docs/DeveloperGuide.md
Labels: type.Task

#53 DG: Add Use Cases - Use Cases 5-9
  docs/DeveloperGuide.md
Labels: type.Task

#45 Update remaining sections of Github README.md, and website index.md
  README.md
  docs/index.md
  docs/team/deseansoh.md
Labels: type.Task

#54 Add Use Case 1-4 in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#69 Create Medical History field to Add and Edit Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#84 Edit help command and message formats
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Task

#86 Update User Guide
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/viewMonday.png
Labels: priority.Low

#118 Add ScheduleConflicts
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/ScheduleConflictDetector.java
  src/main/java/seedu/address/model/person/ScheduleConflictResult.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/ScheduleConflictDetectorTest.java
  src/test/java/seedu/address/model/person/ScheduleConflictResultTest.java
Labels: priority.High

#120 Enable Assertions
  build.gradle
Labels: type.Task

#122 Update version number in project
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug

#123 Bugfix for duplicate phone numbers existing
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#124 UML Activity diagram for help command
  docs/DeveloperGuide.md
  docs/diagrams/HelpCommandActivityDiagram.puml
  docs/images/HelpCommandActivityDiagram.png
Labels: priority.Medium, type.Task

#137 Add ActivityDiagram for AddCommand/EditCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand_EditCommandActivityDiagram.puml
  docs/images/AddCommand_EditCommandActivityDiagram.png
Labels: type.Task
