Repository AY2425S2-CS2103T-T13-1/tp, pull requests merged in 2025-04, with the labels that each got.

#165 Edit grammatical error
  docs/DeveloperGuide.md
Labels: alpha-bug

#175 Update UG to fix typo and Command summary
  docs/UserGuide.md
Labels: alpha-bug

#171 Modify formatting of blocks in UG
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#166 Add hyperlink to edit section under Add Command
  docs/UserGuide.md
Labels: alpha-bug

#168 Fix use case bugs
  docs/DeveloperGuide.md
Labels: severity.Low, alpha-bug

#176 Date parsing bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/OneTimeSchedule.java
  src/main/java/seedu/address/model/util/LocalDateUtils.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/util/LocalDateUtilsTest.java
Labels: severity.Medium, alpha-bug

#160 Schedule - Code Quality Improvement
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/OneTimeSchedule.java
  src/main/java/seedu/address/model/person/RecurringSchedule.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/ScheduleConflictDetector.java
  src/main/java/seedu/address/model/person/ScheduleConflictResult.java
  src/test/java/seedu/address/model/person/OneTimeScheduleTest.java
  src/test/java/seedu/address/model/person/RecurringScheduleTest.java
  src/test/java/seedu/address/model/person/ScheduleConflictDetectorTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: alpha-bug

#179 DG - Update image for ViewCommandActivityDiagram
  docs/images/ViewCommandActivityDiagram.png
Labels: priority.High, alpha-bug

#178 View - Code Quality fixes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/person/OneTimeSchedule.java
  src/main/java/seedu/address/model/person/ScheduleConflictResult.java
  src/main/java/seedu/address/model/person/ScheduleContainsKeywordPredicate.java
  src/main/java/seedu/address/model/util/DayOfWeekUtils.java
  src/main/java/seedu/address/model/util/LocalDateUtils.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/person/ScheduleContainsKeywordPredicateTest.java
Labels: severity.Low, alpha-bug
